---
title: "Lab 00 - Hello IDS!"
author: "YichengJin"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Queency", "esther", "Jasmine", 
           "Eason", "Amanda Liu"),
  github_username = c("qwu07", "estherJjjj", "Mocha0927", 
                      "YichengJin", "amanda21-liu"), 
  colour = c("blue", "white", "pink", 
             "orange", "pink"),
  hobby = c("art", "sports", "playing video games", 
            "music", "playing video games"),
  favourite_number = c(7,3,1,8,6)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```


Two members like pink

### Exercises 19

Change the text of the plot title and axis labels.

```{r labelled-bar-plot}
p1 + labs(x = "github_username", 
          y = "favourite_number",
          title = "fill = colour")
```

Two members like pink

### Exercise 20

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```

Can't tell if many members have the same hobby
